# =========================================
# GRADLE PERFORMANCE
# =========================================

org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# =========================================
# ANDROID
# =========================================

android.useAndroidX=true
android.nonTransitiveRClass=true

# Suppress SDK warning
android.suppressUnsupportedCompileSdk=35

# =========================================
# KOTLIN
# =========================================

kotlin.code.style=official
kotlin.incremental=true

# =========================================
# BUILD SPEED
# =========================================

android.enableJetifier=false
org.gradle.vfs.watch=true
